// Generated by gencpp from file control_package/bBox.msg
// DO NOT EDIT!


#ifndef CONTROL_PACKAGE_MESSAGE_BBOX_H
#define CONTROL_PACKAGE_MESSAGE_BBOX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control_package
{
template <class ContainerAllocator>
struct bBox_
{
  typedef bBox_<ContainerAllocator> Type;

  bBox_()
    : top_left_x(0.0)
    , top_left_y(0.0)
    , width(0.0)
    , height(0.0)  {
    }
  bBox_(const ContainerAllocator& _alloc)
    : top_left_x(0.0)
    , top_left_y(0.0)
    , width(0.0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef double _top_left_x_type;
  _top_left_x_type top_left_x;

   typedef double _top_left_y_type;
  _top_left_y_type top_left_y;

   typedef double _width_type;
  _width_type width;

   typedef double _height_type;
  _height_type height;




  typedef boost::shared_ptr< ::control_package::bBox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_package::bBox_<ContainerAllocator> const> ConstPtr;

}; // struct bBox_

typedef ::control_package::bBox_<std::allocator<void> > bBox;

typedef boost::shared_ptr< ::control_package::bBox > bBoxPtr;
typedef boost::shared_ptr< ::control_package::bBox const> bBoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_package::bBox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_package::bBox_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace control_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'control_package': ['/home/savio/Documents/Ardupilot-Control/src/control_package/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::control_package::bBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_package::bBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_package::bBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_package::bBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_package::bBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_package::bBox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_package::bBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6fed9585f6e4fe60118eae6528781f7c";
  }

  static const char* value(const ::control_package::bBox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6fed9585f6e4fe60ULL;
  static const uint64_t static_value2 = 0x118eae6528781f7cULL;
};

template<class ContainerAllocator>
struct DataType< ::control_package::bBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_package/bBox";
  }

  static const char* value(const ::control_package::bBox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_package::bBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 top_left_x\n\
float64 top_left_y\n\
float64 width\n\
float64 height\n\
";
  }

  static const char* value(const ::control_package::bBox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_package::bBox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.top_left_x);
      stream.next(m.top_left_y);
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bBox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_package::bBox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_package::bBox_<ContainerAllocator>& v)
  {
    s << indent << "top_left_x: ";
    Printer<double>::stream(s, indent + "  ", v.top_left_x);
    s << indent << "top_left_y: ";
    Printer<double>::stream(s, indent + "  ", v.top_left_y);
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_PACKAGE_MESSAGE_BBOX_H
